### ISSUE TITLE
Separate namespaces for cargo dependencies and features

### ISSUE THREAD

**Issue by isislovecruft** [dalek-cryptography/curve25519-dalek#286]
We should probably enable https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#namespaced-features when available to avoid things like our "std" feature trampling/getting trampled by anything using curve25519-dalek with a dependency on an alternative version/implementation of `std`.

**Comment by james-darkfox** [comment]
It is only an issue for the crates that bring their own `std` dependencies - which does not include `curve25519-dalek`. Even then, that'll probably not be an issue as xargo manages that, not `Cargo.toml`.

The consuming crate doesn't need to care if its dependencies have feature names that match its own dependencies.

```toml
[features]
std = ["curve25519-dalek/std"]
# the "std" on the left matters, the "std" on the right is unaffected

# or
[dependencies]
curve25519_dalek = { version = "*", features = ["std"] }
# this "std" is unaffected
std = { path = "custom-std" }
# this cannot coexist with the local feature "std" without the namespace
```
