### ISSUE TITLE
Katex doc rendering

### ISSUE THREAD

**Issue by Shoeboxam** [dalek-cryptography/curve25519-dalek#423]
I was recently trying to get Katex rendering on docs.rs for a crate I work on. Noticed [this crate](https://github.com/alphaville/optimization-engine) was able to get it working. It seems you can directly reference a file in your crate.

```toml
[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "docs/assets/rustdoc-include-katex-header.html"]
```
